### ISSUE TITLE
rash md5 does not match the output of md5sum

### ISSUE THREAD

**Issue by anglerud** [themadprofessor/rash#1]
This migth of course not be a goal of the project at all, but as it doesn't say in the readme I thought I'd point out that i was surprised that `rash md5` of a file doesn't match that of `md5sum`. For example:

```bash
$ echo "abc" > ~/tmp/abc && ./target/release/rash md5 ~/tmp/abc
984a63b68a1c581b6ec1af0c96e6d527
$ md5sum ~/tmp/abc
0bee89b07a248e27c83fc3d5951213c1  /home/anglerud/tmp/abc
```

Similarly for `rash sha1` and `sha1sum`:

```bash
$ echo "abc" > ~/tmp/abc && ./target/release/rash sha1 ~/tmp/abc
6f54f5fef53f1511b89b6bc2e3dd4521b9abcc2e
$ sha1sum ~/tmp/abc
03cfd743661f07975fa2f1220c5194cbaff48451  /home/anglerud/tmp/abc
```

If they're not intended to match - a quick note in the README.md might be a quick solution.

**Comment by themadprofessor** [comment]
That was not intended 😆
I was adding 1024 zero bytes to the file before calculating the hash.
Should be fixed now.

**Comment by anglerud** [comment]
Super, thank you - working like a charm!
